apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: production
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - port: 9898
      targetPort: 9898
      name: http
  type: ClusterIP
